version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    network_mode: host
    restart: always
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: postgres
            database: graphqlsocialpet
            host: localhost
            port: 5432
            user: postgres
            password: postgres
            migrations: true
            ssl: false
            rawAccess: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
